model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: models.core.Restorer
  params:
    ckpt_path: /home/xdy_cbf/CODE_cbf/Destrip/logs/2024-05-13T09-13-26_craters-unet-cl/checkpoints/epoch=000000.ckpt
    monitor: 'validate/loss'
    input_key: 'image'
    lambdas: [1,10,10,1]

    lossconfig:
      target: modules.losses.LPIPS
      params:
        net: 'vgg'
        model_path: /home/xdy_cbf/CODE_cbf/Destrip/pretrained/lpips/vgg.pth
      gen_nce_layers: [0, 2, 4, 8, 12]
    
    # for auto-encoder configuration
    first_stage_config:
      target: models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: /disk527/Datadisk/xdy_cbf/pretrained/models/first_stage_models/kl-32x32x8/epoch=000011-v1.ckpt
        ddconfig:
          double_z: True
          z_channels: 8
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    unet_config:
      resolution: 32
      ch: 8  # for latent channels
      in_channels: 4
      out_ch: 4
      num_res_blocks: 2
      attn_resolutions: [ ]
      ch_mult: [1,2,4]
      use_timestep: False
    
    # for discriminator and generator configuration
    ddconfig: 
      in_channels: 3
      out_ch: 3

    scheduler_config: # 10000 warmup steps
      target: utils.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 20
    train:
      target: data.crater.DTM_Train
      params:
        db_dir: /disk527/Datadisk/xdy_cbf/lunar_crater/textures
        channels: 3
        shape: [960,960]
        crop_sz: [256,256]
        crop_part: [4,4]

    validation:
      target: data.crater.DTM_Validate
      params:
        db_dir: /disk527/Datadisk/xdy_cbf/lunar_crater/textures
        channels: 3
        shape: [960,960]
        crop_sz: [256,256]
        crop_part: [4,4]
        augment_s: False
        augment_t: False
    
    test:
      target: data.crater.DTM_Test
      params:
        db_dir: /disk527/Datadisk/xdy_cbf/lunar_crater/textures
        channels: 3
        shape: [960,960]
        crop_sz: [256,256]
        crop_part: [4,4]
        augment_s: False
        augment_t: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    accumulate_grad_batches: 1